### PR TITLE
Adds UY to the available countries

### PR DESCRIPTION
**Pull request by arianbessonart**
Adds UY as an available country.

### CODE REVIEW

**Comment by dgomes** [comment]
tested ?

**Comment by arianbessonart** [comment]
I was using it selecting "AR", but now it's failing, it's seems they now are validating the contracts belonging to the country.

**Comment by dgomes** [comment]
This PR will not fix that... you will still use the same backend

**Comment by arianbessonart** [comment]
> This PR will not fix that... you will still use the same backend

The BE is working fine, I was using it in Homeassistant selecting the country Argentina. 
The iOS app works fine when I use it with Uruguay.

**Comment by dgomes** [comment]
BE ? 

In practice, choosing Uruguay in this lib will be no different from choosing Argentina...

**Comment by arianbessonart** [comment]
> BE ?
> 
> In practice, choosing Uruguay in this lib will be no different from choosing Argentina...

Oh, you are right... Is the [country list](https://github.com/dgomes/pyprosegur/blob/master/pyprosegur/auth.py#L13) what the home assistant is using for the dropdown? 
If that is the case it would be good to have UY there too.

**Comment by dgomes** [comment]
Yes this only affects the dropdown, but as you seen from the code choosing any country besides Spain will have the same result

**Pull request merged**
